function obj = initialize(obj, varargin)
   
% ============================================================================ %
% ============================================================================ %

current_class = 'remote.rx';

% Start error handling
try

% ============================================================================ %
% ============================================================================ %

% Initialize COMMON.REMOTEOBJ superclass
obj = initialize@common.remoteobj(obj, varargin{1:end});

% ============================================================================ %
% ============================================================================ %

%% Add new parameters

% Id of the filter coefficients
Par = common.remotepar( ...
    'fcId', ...
    'int32', ...
    'sets the filter coefficients id', ...
    {[1 Inf]}, ...
    {'index of filter coefficients'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Clip mode level (default = 0)
Par = common.remotepar( ...
    'clipMode', ...
    'int32', ...
    'sets the clip mode level', ...
    {0 1 2 3}, ...
    {'no clipping', 'maximum clip level', 'medium clip level', ...
        'lowest clip level'}, ...
    obj.Debug, current_class );
Par = Par.setValue(0);
obj = obj.addParam(Par);

% ============================================================================ %

% Receive frequency
Par = common.parameter( ...
    'RxFreq', ...
    'single', ...
    'sets the receive frequency', ...
    {[1 60]}, ...
    {'receive frequency [MHz]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Decimation mode
Par = common.remotepar( ...
    'QFilter', ...
    'int32', ...
    'sets the decimation mode', ...
    {1 2 3}, ...
    {'no decimation', '100% mode', '50% mode'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Harmonic filtering mode (default = 1)
Par = common.remotepar( ...
    'harmonicFilter', ...
    'int32', ...
    'sets the harmonic filtering', ...
    {1 2 0}, ...
    {'no filter', '-15 dB @ < 2 MHz, min @ 3 MHz, to -2.5 dB @ [ 3 5 ] MHz', ...
        '-15 dB @ < 2MHz, min @ 3.75 MHz, to 0 dB @ [ 3 ; 10 ] MHz '}, ...
    obj.Debug, current_class );
Par = Par.setValue(1);
obj = obj.addParam(Par);

% ============================================================================ %

% VGA input filtering
if strcmp( system.hardware.Tag, 'BTE' )
    Par = common.remotepar( ...
        'VGAInputFilter', ...
        'int32', ...
        'sets measurement type', ...
        { 0 3 }, ...
        { 'Intensity measurement', 'Voltage measurement' }, ...
        obj.Debug, current_class );
    Par = Par.setValue(3);
else
    Par = common.remotepar( ...
        'VGAInputFilter', ...
        'int32', ...
        'sets notches to block frequencies', ...
        { 0 4 2 1 }, ...
        { 'no notch', 'notch @ 2.25 MHz', 'notch @ 3.75 MHz', 'notch @ 5.5 MHz' }, ...
        obj.Debug, current_class );
    Par = Par.setValue(0);
end    
obj = obj.addParam(Par);

% ============================================================================ %

% VGA low gain filtering (default = 0)
Par = common.remotepar( ...
    'VGALowGain', ...
    'int32', ...
    'sets a filter for low gain', ...
    { 0 1 }, ...
    { 'no attenuation', '-20 dB after 10 µs' }, ...
    obj.Debug, current_class );
Par = Par.setValue(0);
obj = obj.addParam(Par);

% ============================================================================ %

% Receiving elements
Par = common.parameter( ...
    'RxElemts', ...
    'int32', ...
    'sets the receiving elements', ...
    { 0 [1 system.hardware.NbTxChan] }, ...
    { 'no receiving elements', 'indexes of receiving elements' }, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% HIFU receiving (default = 0)
Par = common.parameter( ...
    'HifuRx', ...
    'int32', ...
    'enables reception on non-contiguous elements', ...
    {0 1}, ...
    {'contiguous receiving channels', 'distinct receiving channels'}, ...
    obj.Debug, current_class );
Par = Par.setValue(0);
obj = obj.addParam(Par);

% ============================================================================ %
% ============================================================================ %

%% End error handling
catch Exception
    
    % Exception in this method
    if ( isempty(Exception.identifier) )
        
        % Emit the new exception
        NewException = ...
            common.legHAL.GetException(Exception, class(obj), 'initialize');
        throw(NewException);

    % Re-emit previous exception
    else
        
        rethrow(Exception);
        
    end
    
end

% ============================================================================ %
% ============================================================================ %

end