function obj = initialize(obj, varargin)
   
% ============================================================================ %
% ============================================================================ %

current_class = 'elusev.hifu';

% Start error handling
try

% ============================================================================ %
% ============================================================================ %

% Initialize superclass
obj = initialize@elusev.elusev(obj, varargin{1:end});

% ============================================================================ %
% ============================================================================ %

%% Add new parameters

% Waveform sampling rate (default = 1)
Par = common.parameter( ...
    'txClock180MHz', ...
    'int32', ...
    'sets the waveform sampling rate', ...
    {0 1}, ...
    {'sampling rate = 90 MHz', 'sampling rate = 180 MHz'}, ...
    obj.Debug, current_class );
Par = Par.setValue(1);
obj = obj.addParam(Par);

% HIFU emission frequency
Par = common.parameter( ...
    'TwFreq', ...
    'single', ...
    'sets the hifu emission frequency', ...
    {[0.5 system.hardware.MaxTxFreq]}, ...
    {'hifu emission frequency [MHz]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% HIFU emission duration
Par = common.parameter( ...
    'TwDuration', ...
    'single', ...
    'sets the hifu emission duration', ...
    {[1 20e6]}, ...
    {'hifu emission duration [us]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% HIFU transmitting elements
Par = common.parameter( ...
    'TxElemts', ...
    'int32', ...
    'sets the emitting elements', ...
    {[1 system.probe.NbElemts]}, ...
    {'emitting elemts'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% HIFU phase offset
Par = common.parameter( ...
    'Phase', ...
    'single', ...
    'sets the hifu emission phase offset', ...
    {[0 2*pi]}, ...
    {'hifu phase offset [rad]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% HIFU duty cycle
Par = common.parameter( ...
    'DutyCycle', ...
    'single', ...
    'sets the hifu duty cycle', ...
    {[0 1]}, ...
    {'hifu duty cycle'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Cavitation receive frequency
Par = common.parameter( ...
    'RxFreq', ...
    'single', ...
    'sets the sampling frequency', ...
    {[0 60]}, ...
    {'sampling frequency [MHz]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Cavitation receive duration
Par = common.parameter( ...
    'RxDuration', ...
    'single', ...
    'sets the acquisition duration', ...
    {0 [1 1e5]}, ...
    {'no cavitation reception' 'cavitation receive duration [us]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Cavitation receiving elements
Par = common.parameter( ...
    'RxElemts', ...
    'int32', ...
    'set the receiving elements', ...
    {0 [1 system.probe.NbElemts]}, ...
    {'no receiving elements' 'receiving elemts'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %
% ============================================================================ %

%% End error handling
catch Exception
    
    % Exception in this method
    if ( isempty(Exception.identifier) )
        
        % Emit the new exception
        NewException = ...
            common.legHAL.GetException(Exception, class(obj), 'initialize');
        throw(NewException);

    % Re-emit previous exception
    else
        
        rethrow(Exception);
        
    end
    
end

% ============================================================================ %
% ============================================================================ %

end