// Scanconvert.ccp 
// M. COUADE 18/09/2007

// ScanConvesion for curved Probe, mex file to use with look up table generated by ScanConverterTable3.m in matlab

#include "math.h"
#include "mex.h"

void ScanConvert(float * LUT_coeff,short * LUT_X, short * LUT_Z ,short * LUT_Vois1, short * LUT_Vois2 ,int NbVois,int LUTSIZE,int Nx,int Ntheta, float * DataOriginal,float * DataFinal)
{
    
    int k,n ;
    int x,y ;
    
    int NbVoisTot = (2*NbVois) ;
    int SeekOffSet = 0 ;
    
    float Data = 0 ;
    short * Vois1 ;
    short * Vois2 ;
    
    //float * coeff ;
    //float * value ;
    
    NbVoisTot*= NbVoisTot ;
    mexPrintf("NbVoisTot = %d\n",NbVoisTot);
    mexPrintf("LUTSIZE = %d\n",LUTSIZE);

    //coeff = (float*)malloc(sizeof(float)*NbVoisTot);
    //value = (float*)malloc(sizeof(float)*NbVoisTot);
   
    for(k=0;k<LUTSIZE;k++)
    {
        
        SeekOffSet = k*NbVoisTot ;
        
        Vois1 = LUT_Vois1 + SeekOffSet;
        Vois2 = LUT_Vois2 + SeekOffSet;
        
        /*
        for(n=0;n<NbVoisTot;n++)
        {
            coeff[n] = LUT_coeff[n + SeekOffSet] ;
            value[n] = DataOriginal[Vois1[n]+Ntheta*Vois2[n]];
        }
                      
        x = (int)LUT_X[k];
        y = (int)LUT_Z[k];
               
        Data = coeff[0]*value[0];
       
        for(n=1;n<NbVoisTot;n++)
        {        
            Data += coeff[n]*value[n];
        }*/
        
        Data = 0;
        for(n=0;n<NbVoisTot;n++)
        {
            float a = LUT_coeff[n + SeekOffSet] ;
            float b = DataOriginal[Vois1[n]+Ntheta*Vois2[n]];
            Data += a*b;  
        }
                      
        x = (int)LUT_X[k];
        y = (int)LUT_Z[k];
        
       DataFinal[x+Nx*y] = (Data) ;
    }
    //DataFinal[0] = Data ;

    //free(coeff);
    //free(value);
}
/*
void ScanConvertTest(double * LUT_coeff,double * LUT_XZ,double * LUT_Vois,int NbVois,int LUTSIZE,int Nx,int Ntheta, double * DataOriginal,double * DataFinal)
{
    
	int NbVoisTot = (2*NbVois)^2 ;
	mexPrintf("NbVoisTot = %d\n",NbVoisTot);
	mexPrintf("LUTSIZE = %d\n",LUTSIZE);

	int k,n ;
	int x,y ;

	int vois1, vois2 ;
	double coeff ;

	k = 1000 ;


	x = (int)LUT_XZ[k];
	y = (int)LUT_XZ[k+LUTSIZE];

	x-- ; // indices in matlab starts from 1
	y-- ; // indices in matlab starts from 1

	mexPrintf("LUT_XZ(%d,1,1) = %d ; LUT_XZ(%d,2,1) = %d\n",k+1,x+1,k+1,y+1);


	vois1 =  (int)LUT_Vois[k];
	vois2 =  (int)LUT_Vois[k+LUTSIZE];

	
	vois1-- ; // indices in matlab starts from 1
	vois2-- ; // indices in matlab starts from 1

	mexPrintf("LUT_Vois(%d,1,1) = %d ; LUT_Vois(%d,2,1) = %d\n",k+1,vois1+1,k+1,vois2+1);

	n = 8 ;

	vois1 =  (int)LUT_Vois[k+n*LUTSIZE*2];
	vois2 =  (int)LUT_Vois[k+LUTSIZE+n*LUTSIZE*2];

	vois1-- ; // indices in matlab starts from 1
	vois2-- ; // indices in matlab starts from 1

	mexPrintf("LUT_Vois(%d,1,%d) = %d ; LUT_Vois(%d,2,%d) = %d\n",k+1,n+1,vois1+1,k+1,n+1,vois2+1);

	coeff = LUT_coeff[k+LUTSIZE*n];
	mexPrintf("LUT_coeff(%d,%d) = %g",k+1,n+1,coeff);
	x = 250 ;
	y = 500 ;
	
	DataFinal[0] = -10 ;

	vois1 = 60 ;
	vois2 = 70 ;

	mexPrintf("DataOriginal(%d,%d) = %g",vois1+1,vois2+1,DataOriginal[vois1+Ntheta*vois2]) ;
      
    
}*/

void mexFunction(int nlhs, mxArray *plhs[],int nrhs, const mxArray *prhs[])
{    
    
    float * LUT_coeff ;
    short * LUT_X, * LUT_Z ;
    short * LUT_Vois1, * LUT_Vois2 ;
    
    float * DataOriginal ;
    float * DataFinal ;
    
    int NbVois ;
    int LUTSIZE ;
    
    int Nx, Ntheta ;
    
    LUT_coeff = (float*)mxGetPr(prhs[0]);
    LUT_X = (short*)mxGetPr(prhs[1]);
    LUT_Z = (short*)mxGetPr(prhs[2]);
    LUT_Vois1 = (short*)mxGetPr(prhs[3]);
    LUT_Vois2 = (short*)mxGetPr(prhs[4]);
    NbVois = (int)(*(double*)mxGetPr(prhs[5]));
    LUTSIZE = (int)(*(int*)mxGetPr(prhs[6]));
    DataOriginal = (float*)mxGetPr(prhs[7]);
    DataFinal = (float*)mxGetPr(prhs[8]);
    
    Nx = mxGetM(prhs[8]); // Get the number of column in DataFinal
    Ntheta = mxGetM(prhs[7]); // Get the number of column in DataOriginal
    mexPrintf("Ne = %d\n",Nx);
    ScanConvert(LUT_coeff,LUT_X,LUT_Z,LUT_Vois1,LUT_Vois2,NbVois,LUTSIZE,Nx,Ntheta,DataOriginal,DataFinal); // Call scanconvert
       
}

