function obj = initialize(obj, varargin)
   
% ============================================================================ %
% ============================================================================ %

current_class = 'elusev.push';

% Start error handling
try

% ============================================================================ %
% ============================================================================ %

% Initialize superclass
obj = initialize@elusev.elusev(obj, varargin{1:end});

% ============================================================================ %
% ============================================================================ %

%% Add new parameters

% Push emission frequency
Par = common.parameter( ...
    'TwFreq', ...
    'single', ...
    'sets the push emission frequency', ...
    {[1 system.hardware.MaxTxFreq]}, ...
    {'push emission frequency [MHz]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Push emission duration
Par = common.parameter( ...
    'PushDuration', ...
    'single', ...
    'sets the push emission duration', ...
    {[1 300]}, ...
    {'push emission duration [us]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Push event duration
Par = common.parameter( ...
    'Duration', ...
    'single', ...
    'sets the push event duration', ...
    {[5 1000]}, ...
    {'push event duration [us]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Maximum duty cycle
Par = common.parameter( ...
    'DutyCycle', ...
    'single', ...
    'sets the maximum duty cycle', ...
    {[0 1]}, ...
    {'maximum duty cycle'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Lateral position of the focus
Par = common.parameter( ...
    'PosX', ...
    'single', ...
    'sets the focus lateral position', ...
    {[0 100]}, ...
    {'lateral position [mm]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Axial position of the focus
Par = common.parameter( ...
    'PosZ', ...
    'single', ...
    'sets the focus axial position', ...
    {[0 100]}, ...
    {'axial position [mm]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Aperture center position
Par = common.parameter( ...
    'TxCenter', ...
    'single', ...
    'sets the emitting center position', ...
    {[0 100]}, ...
    {'aperture center position [mm]'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Ratio F/D
Par = common.parameter( ...
    'RatioFD', ...
    'single', ...
    'sets the ratio F/D', ...
    {[0 1000]}, ...
    {'ratio F/D'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %

% Apodisation function
Par = common.parameter( ...
    'ApodFct', ...
    'char', ...
    'sets the apodisation function', ...
    {'none' 'bartlett' 'blackman' 'connes' 'cosine' 'gaussian' 'hamming' ...
        'hanning' 'welch'}, ...
    {'no apodisation' 'bartlett function' 'blackman function' ...
        'connes function' 'cosine function' 'gaussian function' ...
        'hamming function' 'hanning function' 'welch function'}, ...
    obj.Debug, current_class );
obj = obj.addParam(Par);

% ============================================================================ %
% ============================================================================ %

%% End error handling
catch Exception
    
    % Exception in this method
    if ( isempty(Exception.identifier) )
        
        % Emit the new exception
        NewException = ...
            common.legHAL.GetException(Exception, class(obj), 'initialize');
        throw(NewException);

    % Re-emit previous exception
    else
        
        rethrow(Exception);
        
    end
    
end

% ============================================================================ %
% ============================================================================ %

end